name: fin_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  
  camera: ^0.10.5+2
  chewie: ^1.7.0
  cloud_firestore: ^4.8.1
  collection: ^1.17.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  file_picker: ^5.3.2
  firebase_analytics: ^10.4.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.0.3
  geolocator: ^9.0.2
  go_router: ^8.0.5
  http: ^0.13.0
  image_cropper: ^4.0.1
  image_picker: ^0.8.9
  intl: ^0.18.1
  json_annotation: ^4.8.1
  
  loading_animation_widget: ^1.2.0+4
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  shared_preferences: ^2.1.2
  shimmer: ^3.0.0
  uuid: ^3.0.7
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/2.jpg
    - assets/profile.png
